### PR TITLE
Fixed the deprecate method compiler warnings for the JSON parsing for MQTT messages

### PR DESCRIPTION
**Pull request by Martinius79**
Fixed the deprecate method compiler warnings for the JSON parsing for MQTT messages.

containskey() method from ArduinoJSON is marked as deprecated and is now replaced in the code.

Tested with (and without) Home Assistant integration active.

See: https://arduinojson.org/v7/api/jsondocument/containskey/

### CODE REVIEW

**Comment by eku** [comment]
May I suggest that you please only make changes to the content and leave the formatting as it is?

**Comment by Martinius79** [comment]
Hello eku!

With "formatting as it is" I guess you mean the seven new lines and the two changed intents :)
I removed these changes with the last commit.

The only way to avoid "this problem" (which you also now a lot, I guess) is to use a defined formatting rule set...And this is available in the C/C++ Extension of Visual Studio Code already. It uses some dafault settings with the CLang formatter. 

If you press Alt+Shift+F, the actual opened document in VS Code, it will be formatted by the defined default rule set.

I did this for the actual C++ source code as an example in the follwing branch: 
https://github.com/Martinius79/EleksTubeHAX/tree/mainCLangFormatted

I don't "love" the default formatting, but it would be an idea, that all contributers use the "format document" method on changed files, to have a common working basis as the lowest common denominator.

Bye
Martinius

**Comment by aly-fly** [comment]
One conflict is here. Please check and resolve.

**Comment by Martinius79** [comment]
Done

**Comment by eku** [comment]
> The best way to avoid formatting inconsistencies is indeed by using a defined formatting rule set.

If there are no explicit rules, then format the code like the existing one. Turn off all the magic of the IDE.

Well, at least configure your IDE to only format changed lines and leave the rest as is. VIM suports it :)

**Pull request merged**
